Document: cadexsdk
Title: Debian cadexsdk Manual
Author: <insert document author here>
Abstract: This manual describes what cadexsdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cadexsdk/cadexsdk.sgml.gz

Format: postscript
Files: /usr/share/doc/cadexsdk/cadexsdk.ps.gz

Format: text
Files: /usr/share/doc/cadexsdk/cadexsdk.text.gz

Format: HTML
Index: /usr/share/doc/cadexsdk/html/index.html
Files: /usr/share/doc/cadexsdk/html/*.html
